### ISSUE TITLE
 sender:BQ:create_table:error Error: Already Exists:

### ISSUE THREAD

**Issue by scaryguy** [AfterShip/demo_streamer2bigquery#1]
Hi there,

When I clone and run your demo repository from scratch, I get this error:

```
demo_streamer2bigquery [master●] DEBUG=* node streamer.js
i started
  streamer:google_client:log   authorized +0ms
  scheduler:log   added new sender for key:logs:demo_app:v2:random_address +5ms
  sender:BQ:create_dataset:error Error: Already Exists: Dataset seismic-spot-114600:development_demo_app_v2
___Stack trace #1___
Error: Already Exists: Dataset my_dataset:development_demo_app_v2
    at Request._callback (/Users/scaryguy/arge/redis_to_bq/demo_streamer2bigquery/node_modules/bigquery-streamer/node_modules/googleapis/lib/transporters.js:83:15)
    at Request.self.callback (/Users/scaryguy/arge/redis_to_bq/demo_streamer2bigquery/node_modules/bigquery-streamer/node_modules/googleapis/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/scaryguy/arge/redis_to_bq/demo_streamer2bigquery/node_modules/bigquery-streamer/node_modules/googleapis/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/scaryguy/arge/redis_to_bq/demo_streamer2bigquery/node_modules/bigquery-streamer/node_modules/googleapis/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17) +2s
```

But I don't have mentioned table. It is created after I run `streamer.js`. So what could be wrong?

Thanks

**Comment by scaryguy** [comment]
Seems like `bigquery-streamer` is pretty old. Do you have any working demos with V3 of `bigquery-streamer`?
